//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int NumeroCliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int TipoDocumento { get; set; }
        public string Documento { get; set; }
        public int Sexo { get; set; }
        public string RazonSocial { get; set; }
        public System.DateTime Nacimiento { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string LugarTrabajo { get; set; }
        public int AntiguedadLaboral { get; set; }
        public string DireccionLaboral { get; set; }
    }
}
