//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobranza_detalle
    {
        public int cobdet_id { get; set; }
        public int cobcab_nro { get; set; }
        public int cobdet_preid { get; set; }
        public int cobdet_mora { get; set; }
        public Nullable<int> cobdet_dcto { get; set; }
    }
}
