//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobranza_cheque
    {
        public int cobcheque_codigo { get; set; }
        public string cobcheque_tipo { get; set; }
        public string cobcheque_nro { get; set; }
        public int cob_nro { get; set; }
        public System.DateTime cobcheque_fecha { get; set; }
        public int cobcheque_monto { get; set; }
    }
}
