//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuCredito.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comentario
    {
        public int Id { get; set; }
        [StringLength(50, ErrorMessage = "{0} debe tener al menos {2} caracteres de longitud ", MinimumLength = 3)]
        public string Nombre { get; set; }
        [StringLength(50, ErrorMessage = "{0} debe tener al menos {2} caracteres de longitud ", MinimumLength = 3)]
        public string Apellido { get; set; }
        [StringLength(50, ErrorMessage = "{0} debe tener al menos {2} caracteres de longitud ", MinimumLength = 15)]
        [Display(Name = "Comentarios")]
        public string Comentario1 { get; set; }
    }
}
