//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moneda
    {
        public string mon_codigo { get; set; }
        public string mon_descripcion { get; set; }
        public string mon_pais { get; set; }
    }
}
