//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public int NumeroEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Documento { get; set; }
        public int Cargo { get; set; }
        public System.DateTime FechaNac { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public int TipoDeDocumento { get; set; }
        public int Sexo { get; set; }
    }
}
