//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamo_detalle
    {
        public int predet_id { get; set; }
        public int predet_nrocabecera { get; set; }
        public int predet_nrocuota { get; set; }
        public int predet_monto { get; set; }
        public int predet_saldo { get; set; }
        public System.DateTime predet_vencimiento { get; set; }
        public string predet_estado { get; set; }
    }
}
