//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamo
    {
        public int pre_numero { get; set; }
        public System.DateTime pre_fecha { get; set; }
        public int pre_cliente { get; set; }
        public string pre_tipoprestamo { get; set; }
        public int pre_montosolicitado { get; set; }
        public string pre_moneda { get; set; }
        public int pre_cantcuota { get; set; }
        public int pre_interes { get; set; }
        public int pre_montototal { get; set; }
        public string usuario { get; set; }
    }
}
